version: '3.8'

services:
  next:
    image: ${IMAGE}
    ports:
      - '3000:3000'
    networks:
      - nginx_ranjabi_network
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    expose:
      - '5432'
    networks:
      - nginx_ranjabi_network
    environment:
      - POSTGRES_DB=task-tracker-prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./data/postgres-prod:/var/lib/postgresql/data

networks:
  nginx_ranjabi_network:
    external: true