version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=task-tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data