version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - nginx_network
    depends_on:
      - next
  next:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '3000:3000'
    networks:
      - nginx_network
    environment:
      - DATABASE_URL=postgresql://postgres:secret@postgres:5432/task-tracker-dev?schema=public
    volumes:
      - ./:/app
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    networks:
      - nginx_network
    environment:
      - POSTGRES_DB=task-tracker-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./data/postgres-dev:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge