import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="max-w-screen-sm mx-auto">
        <section className="bg-gray-200">
          <nav>this is nav</nav>
        </section>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
